use_frameworks!

platform :ios, '10.0'

target 'OPAttributeString_Example' do
  pod 'OPAttributeString', :path => '../'

  target 'OPAttributeString_Tests' do
    inherit! :search_paths

    
  end
end
